name: Check submission for US-RSE'24

on:
  push:

jobs:
  check-submission:
    uses: USRSE/notebooks-submissions/.github/workflows/check-submission.yml@a08f76ed216de8de2da61f421eba024f17103a78
    with:
      notebook: my_doc.ipynb
      repository: ${{ github.repository }}
      ref: ${{ github.sha }}
      binder-cache-branch: binder-cache
      build-artifacts: |
        my_doc.html
