name: Check submission for US-RSE'24

on:
  push:

jobs:
  check-submission:
    uses: lbianchi-lbl/notebooks-ci/.github/workflows/check-submission.yml@05f445563ef2cf10c6293e709a98efa4c22ba55f
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.sha }}
      reproducible-document: my_doc.ipynb