name: Check submission for US-RSE'24

on:
  push:

jobs:
  check-submission:
    uses: lbianchi-lbl/notebooks-ci/.github/workflows/check-submission.yml@75690b81d05a8f30e6403ac42c0cccb1328d2684
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.sha }}
      binder-cache-branch: binder-cache
      build-artifacts: |
        my_doc.html
