name: Check submission for US-RSE'24

on:
  push:

jobs:
  check-submission:
    uses: lbianchi-lbl/notebooks-ci/.github/workflows/check-submission.yml@4333daf37d1cedceb06d3f34b5e599d6b6a94cec
    with:
      notebook: my_doc.ipynb
      repository: ${{ github.repository }}
      ref: ${{ github.sha }}
      binder-cache-branch: binder-cache
      build-artifacts: |
        my_doc.html
