name: Check submission for US-RSE'24

on:
  push:

jobs:
  check-submission:
    uses: USRSE/notebooks-submissions/.github/workflows/check-submission.yml@c1109fbbbb3040f060e6cda3071eb39fa5065841
    with:
      notebook: my_doc.ipynb
      repository: ${{ github.repository }}
      ref: ${{ github.sha }}
      binder-cache-branch: binder-cache
      build-artifacts: |
        my_doc.html
