name: Check submission for US-RSE'24

on:
  push:

jobs:
  check-submission:
    uses: lbianchi-lbl/notebooks-ci/.github/workflows/check-submission.yml@84fb5dd3a581f5ce66c78d1b5ff31d02e3aeda50
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.sha }}
      binder-cache-branch: binder-cache
      build-artifacts: |
        my_doc.html
