name: Check submission for US-RSE'24

on:
  push:

jobs:
  check-submission:
    uses: USRSE/notebooks-submissions/.github/workflows/check-submission.yml@228c3ce27c977c30d15c2356cd42649b04d5e7ad
    with:
      notebook: my_doc.ipynb
      repository: ${{ github.repository }}
      ref: ${{ github.sha }}
      binder-cache-branch: binder-cache
      build-artifacts: |
        my_doc.html
